"""initial schema

Revision ID: 9511e0ed9499
Revises:
Create Date: 2026-07-10 23:23:10.645313

"""

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision = "9511e0ed9499"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("base_url", sa.String(length=2048), nullable=False),
        sa.Column(
            "platform",
            sa.Enum("wordpress", "html", name="platform", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("crawl_frequency", sa.String(length=50), server_default="manual", nullable=False),
        sa.Column("wp_username", sa.String(length=255), nullable=True),
        sa.Column("wp_app_password", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("base_url"),
    )
    op.create_table(
        "articles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("content_text", sa.Text(), nullable=False),
        sa.Column("content_html", sa.Text(), nullable=True),
        sa.Column("language", sa.String(length=10), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("site_id", "external_id"),
        sa.UniqueConstraint("site_id", "url"),
    )
    op.create_index(op.f("ix_articles_site_id"), "articles", ["site_id"], unique=False)
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "running", "succeeded", "failed", name="run_status", native_enum=False, length=20
            ),
            server_default="running",
            nullable=False,
        ),
        sa.Column("articles_upserted", sa.Integer(), server_default="0", nullable=False),
        sa.Column("links_found", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ingestion_runs_site_id"), "ingestion_runs", ["site_id"], unique=False)
    op.create_table(
        "taxonomies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("category", "tag", name="taxonomy_kind", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("site_id", "kind", "name"),
    )
    op.create_index(op.f("ix_taxonomies_site_id"), "taxonomies", ["site_id"], unique=False)
    op.create_table(
        "article_taxonomies",
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("taxonomy_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["taxonomy_id"], ["taxonomies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("article_id", "taxonomy_id"),
    )
    op.create_table(
        "embeddings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("vector", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("article_id", "model"),
    )
    op.create_index(op.f("ix_embeddings_article_id"), "embeddings", ["article_id"], unique=False)
    op.create_table(
        "internal_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_article_id", sa.Integer(), nullable=False),
        sa.Column("target_article_id", sa.Integer(), nullable=False),
        sa.Column("anchor_text", sa.Text(), nullable=True),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["source_article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_article_id", "target_article_id"),
    )
    op.create_index(
        op.f("ix_internal_links_source_article_id"),
        "internal_links",
        ["source_article_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_internal_links_target_article_id"),
        "internal_links",
        ["target_article_id"],
        unique=False,
    )
    op.create_table(
        "suggestions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("source_article_id", sa.Integer(), nullable=False),
        sa.Column("target_article_id", sa.Integer(), nullable=False),
        sa.Column(
            "method",
            sa.Enum(
                "baseline_cosine",
                "gnn_graphsage",
                name="suggestion_method",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "approved",
                "rejected",
                "applied",
                name="suggestion_status",
                native_enum=False,
                length=20,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("anchor_text", sa.Text(), nullable=True),
        sa.Column("llm_model", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_suggestions_site_id"), "suggestions", ["site_id"], unique=False)
    op.create_index(
        op.f("ix_suggestions_source_article_id"), "suggestions", ["source_article_id"], unique=False
    )
    op.create_index(
        "ix_suggestions_status_created_at", "suggestions", ["status", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_suggestions_target_article_id"), "suggestions", ["target_article_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_suggestions_target_article_id"), table_name="suggestions")
    op.drop_index("ix_suggestions_status_created_at", table_name="suggestions")
    op.drop_index(op.f("ix_suggestions_source_article_id"), table_name="suggestions")
    op.drop_index(op.f("ix_suggestions_site_id"), table_name="suggestions")
    op.drop_table("suggestions")
    op.drop_index(op.f("ix_internal_links_target_article_id"), table_name="internal_links")
    op.drop_index(op.f("ix_internal_links_source_article_id"), table_name="internal_links")
    op.drop_table("internal_links")
    op.drop_index(op.f("ix_embeddings_article_id"), table_name="embeddings")
    op.drop_table("embeddings")
    op.drop_table("article_taxonomies")
    op.drop_index(op.f("ix_taxonomies_site_id"), table_name="taxonomies")
    op.drop_table("taxonomies")
    op.drop_index(op.f("ix_ingestion_runs_site_id"), table_name="ingestion_runs")
    op.drop_table("ingestion_runs")
    op.drop_index(op.f("ix_articles_site_id"), table_name="articles")
    op.drop_table("articles")
    op.drop_table("sites")
    # ### end Alembic commands ###
