"""scope site base_url uniqueness to the owning tenant

Revision ID: d4f2a8c61b93
Revises: b1c4e9a2f780
Create Date: 2026-08-05

Global uniqueness on ``sites.base_url`` predates tenancy. It stops two clients
from owning the same URL — an agency and the brand itself, or a domain moving
between tenants — and it leaks inventory: a tenant learns another tenant holds
a URL from the 409 alone.

The upgrade is safe on existing data because every row currently belongs to the
seeded ``default`` tenant, so the composite constraint cannot collide. The
downgrade can fail by design: once two tenants share a URL, global uniqueness is
no longer satisfiable and the operator must resolve the duplicates first.
"""

import sqlalchemy as sa
from alembic import op

revision = "d4f2a8c61b93"
down_revision = "b1c4e9a2f780"
branch_labels = None
depends_on = None

_GLOBAL_CONSTRAINT = "sites_base_url_key"
_SCOPED_CONSTRAINT = "uq_sites_tenant_base_url"


def upgrade() -> None:
    op.create_unique_constraint(_SCOPED_CONSTRAINT, "sites", ["tenant_id", "base_url"])
    # Autogenerated names vary by how the table was first created; drop only
    # what is actually there so this runs on both migrated and fresh databases.
    op.execute(sa.text(f'ALTER TABLE sites DROP CONSTRAINT IF EXISTS "{_GLOBAL_CONSTRAINT}"'))


def downgrade() -> None:
    duplicates = (
        op.get_bind()
        .execute(
            sa.text(
                "SELECT base_url, count(*) AS n FROM sites "
                "GROUP BY base_url HAVING count(*) > 1 LIMIT 5"
            )
        )
        .fetchall()
    )
    if duplicates:
        listed = ", ".join(f"{row.base_url} ({row.n} tenants)" for row in duplicates)
        raise RuntimeError(
            "cannot restore global base_url uniqueness while these URLs are held "
            f"by more than one tenant: {listed}"
        )
    op.create_unique_constraint(_GLOBAL_CONSTRAINT, "sites", ["base_url"])
    op.drop_constraint(_SCOPED_CONSTRAINT, "sites", type_="unique")
