#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Run from the backend repo root, so .env and docker-compose.yml resolve
# whatever directory the wizard was invoked from.
cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 1

TOTAL_STAGES=4
TOTAL_MINUTES=7

# ── Local helpers ─────────────────────────────────────────────────────────
# There is no jq on this box and the fields we need are flat scalars inside a
# known shape, so targeted matches beat adding a dependency to a setup script.

_tg() { # _tg METHOD — call the Bot API with the token gathered in stage 1
  curl -sS --max-time 15 "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/$1" 2>/dev/null || true
}

_json_str() { # _json_str KEY JSON
  printf '%s' "$2" | grep -oE "\"$1\":\"[^\"]*\"" | head -n1 | sed -E "s/\"$1\":\"(.*)\"/\1/" || true
}

# The last message's sender. `from` has no nested object, so one block match is
# unambiguous; the last one is the most recent thing the human sent.
_last_from() { printf '%s' "$1" | grep -oE '"from":\{[^}]*\}' | tail -n1 || true; }

banner "LinkMesh dashboard login — Telegram setup"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Create the bot" 3
say "Telegram is the identity provider for the dashboard. You need one bot,"
say "and only a human can create it — that is what this stage is for."
printf '\n'
open_url "https://t.me/BotFather"
step "In the BotFather chat, send:  /newbot"
step "Display name — anything readable, e.g.  LinkMesh Dashboard"
step "Username — must be unique and end in 'bot', e.g.  LinkMeshDashboardBot"
step "BotFather replies with a token like  123456789:AAF-xxxxxxxxxxxxxxxxxxxx"
printf '\n'
note "The token is the bot's password. Anyone holding it controls the bot,"
note "so it goes in .env and never into git."
printf '\n'
ask_secret TELEGRAM_BOT_TOKEN "Paste the token:"

if [[ -z "$TELEGRAM_BOT_TOKEN" ]]; then
  warn "No token entered — cannot continue."
  exit 1
fi

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Check the token works" 1
say "Asking Telegram who this token belongs to, so a typo surfaces now"
say "rather than as a silent login failure later."
printf '\n'
GETME=$(_tg getMe)

if [[ "$GETME" != *'"ok":true'* ]]; then
  warn "Telegram rejected that token."
  note "Response: ${GETME:-<empty — check your network connection>}"
  note "Re-run this wizard and paste the token again."
  exit 1
fi

TELEGRAM_BOT_USERNAME=$(_json_str username "$GETME")
BOT_LABEL=$(_json_str first_name "$GETME")
if [[ -z "$TELEGRAM_BOT_USERNAME" ]]; then
  warn "Could not read the username from Telegram's reply."
  ask TELEGRAM_BOT_USERNAME "Type the bot username (no leading @):"
fi
printf '  %s✓%s Token valid — bot is %s%s%s (@%s)\n' \
  "$GREEN" "$RESET" "$BOLD" "${BOT_LABEL:-unnamed}" "$RESET" "$TELEGRAM_BOT_USERNAME"
printf '\n'
write_env TELEGRAM_BOT_TOKEN "$TELEGRAM_BOT_TOKEN"
write_env TELEGRAM_BOT_USERNAME "$TELEGRAM_BOT_USERNAME"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Identify the first admin" 2
say "The first person to log in has nobody to approve them, so one Telegram"
say "account is pre-approved and admits everyone else. That is you."
printf '\n'
say "We read your account ID from your own bot, so no third-party 'what is my"
say "ID' bot ever sees who you are."
printf '\n'
open_url "https://t.me/${TELEGRAM_BOT_USERNAME}"
step "The chat with your new bot should open."
step "Press START (or send any message — 'hi' is fine)."
printf '\n'
pause "Done that? Press Enter and I'll read it back."

UPDATES=$(_tg getUpdates)
FROM=$(_last_from "$UPDATES")
ADMIN_ID=$(printf '%s' "$FROM" | grep -oE '"id":[0-9]+' | head -n1 | grep -oE '[0-9]+' || true)
ADMIN_NAME=$(_json_str first_name "$FROM")

while [[ -z "$ADMIN_ID" ]]; do
  warn "No message from you has reached the bot yet."
  note "Make sure you pressed START in the chat with @${TELEGRAM_BOT_USERNAME}."
  if confirm "Try reading it again?"; then
    UPDATES=$(_tg getUpdates)
    FROM=$(_last_from "$UPDATES")
    ADMIN_ID=$(printf '%s' "$FROM" | grep -oE '"id":[0-9]+' | head -n1 | grep -oE '[0-9]+' || true)
    ADMIN_NAME=$(_json_str first_name "$FROM")
  else
    ask ADMIN_ID "Enter your numeric Telegram ID by hand:"
    if [[ -z "$ADMIN_ID" ]]; then
      warn "Nothing entered — stopping here rather than looping."
      note "The token and username are saved; re-run to finish this stage."
      exit 1
    fi
  fi
done

printf '\n'
printf '  %sFound:%s %s (ID %s)\n' "$BOLD" "$RESET" "${ADMIN_NAME:-unknown}" "$ADMIN_ID"
printf '\n'
if ! confirm "Is that you, and should this account be the first admin?"; then
  ask ADMIN_ID "Enter the Telegram ID that should be first admin instead:"
fi
write_env DASHBOARD_BOOTSTRAP_ADMIN_ID "$ADMIN_ID"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Load the new settings" 1
say "docker-compose reads .env at container start, so the API and worker need"
say "a restart before they can see any of this."
printf '\n'
if confirm "Restart the api and worker containers now?"; then
  if docker compose restart api worker; then
    printf '  %s✓%s Containers restarted.\n' "$GREEN" "$RESET"
  else
    SKIPPED+=("restart the containers: docker compose restart api worker")
    warn "Restart failed — do it by hand when convenient."
  fi
else
  SKIPPED+=("restart the containers: docker compose restart api worker")
  note "Skipped. Run 'docker compose restart api worker' when you're ready."
fi

finish

note "Next: the bot worker that listens for /start is not built yet, so logging"
note "in end to end will not work until that lands. These values are what it needs."
printf '\n'
